theme: jekyll-theme-hacker
title: Qwiklabs
description: Hands on Labs on GCP & AWS made easier with this Repository

author:
  name: "Pradyumna Krishna"
  email: "contact@pradyumna"
  url: "pradyumnakrishna.github.io"

twitter_username: iPradyumnaK
github_username:  PradyumnaKrishna
